version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    networks:
      - caddy-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - caddy-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

networks:
  caddy-net:
    driver: overlay
    attachable: true
    name: caddy-net

volumes:
  caddy_data:
  caddy_config:
  portainer_data: